name: gtsr
channels:
  - conda-forge

dependencies:
  - python=3.10
  - zeopp-lsmo
  - molSimplify==1.8.0
  - openbabel-wheel==3.1.1.23
  - pip
  - pip:
      - gtsr
      - ase>=3.19
      - pymatgen>=2018.6.11
      - scikit-learn==1.3.2
      - rdkit
      - streamlit>=1.36
      - stmol>=0.0.9
      - ipython_genutils>=0.2
      - streamlit_extras
      - torch>=1.12
